export { default as Add } from './Add';
export { default as Menu } from './Menu';
export { default as Home } from './Home';
export { default as MoreVert } from './MoreVert';
export { default as PowerSettings } from './PowerSettings';
export { default as Search } from './Search';
export { default as Favorite } from './Favorite';
export { default as Room } from './Room';
export { default as Work } from './Work';
